Month 9/step 2
Maichonok/stellar-burger pull request #5
Opened 2023-02-07 10:19 UTC by Maichonok

2023-02-07 14:09 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали очень хорошую работу по добавлению сокетов и лент заказов в ваш проект, корректно создали мидлвару и подключили её, отлично сверстали новые экраны, аккуратно провели рефакторинг предыдущих, так держать 👍 

Тем не менее, для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- Проект не запускается по причине отличия регистра имени в `import` и в названии директории компонента `IngredientsModal` (см. https://disk.yandex.ru/i/iigns_2rKvqQ0Q). Обратите внимание, что этот момент важен на регистрозависимых системах, таких как Windows и может упускаться из виду на UNIX-подобных, в частности на MacOS или любой версии Linux;
- Не следует открывать сокет истории заказов пользователя, пока пользователь еще не зашёл в систему. Следует открывать его только на соответствующей странице. (см. https://disk.yandex.ru/i/k5idAqd-sBmdsg);
- Следует закрывать сокеты при уходе с соответствующих экранов, чтобы они не оставались на фоне.  (https://disk.yandex.ru/i/odLVdl878JGqcA);
- Согласно дизайну, у кнопки "История заказов" нет переноса текста, а также слева следует подсвечивать только активную страницу, например на скриншоте находясь в "Истории заказов" подсвечивается также и "Профиль" (см. https://disk.yandex.ru/i/JCytef7RW5ML4A);
- Кнопки "Отменить" и "Сохранить" в профиле следует скрыть, если не были введены новые данные и после успешной их отправки на сервер;

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу, в том числе:

- Не рекомендуется использовать индексы в качестве значения пропса `key` при итерации в JSX, так как это может приводить к дополнительным рендерам, лучше выбирать идентификаторы элементов или генерировать их самостоятельно, главное, чтобы если элемент не изменился - то и его значение `key` не должно меняться;
- Для отображения даты лучше использовать готовый компонент `FormattedDate` из библиотеки компонентов;
- Обратите внимание, что код карточки заказа в "ленте" и в "истории" очень схож, имеет смысл сделать единый компонент для отображения и там и там :)

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

_Если у вас возникнут вопросы относительно комментариев к коду - пишите их в соответствующем треде или передайте их через вашего куратора. Обязательно найдём самое лучшее решение :)_

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2023-02-07 14:09 UTC, randomroot commented on src/components/FeedItemModal/FeedItemModal.jsx
> +  let history = useHistory();
🟡 **Можно улучшить:**

**Здесь и далее по коду:**
Т.к. значение переменной не изменяется далее в коде, то её можно сделать константой `const`. Изменение значений массива или объекта не считается изменением переменной.

2023-02-07 14:09 UTC, randomroot commented on src/components/Board/OrdersBoard.jsx
> +    <>
🟡 **Можно улучшить:**

Использование `React.Fragment` в данном случае нецелесообразно, т.к. у вас есть далее `<div>` который будет служить родительским контейнером

2023-02-07 14:09 UTC, randomroot commented on src/components/Board/OrdersBoard.jsx
> +                  key={index}
🟡 **Можно улучшить:**

В качестве индекса лучше использовать идентификатор заказа, как более уникальный элемент, вместо индекса, чтобы было меньше ререндера

2023-02-07 14:09 UTC, randomroot commented on src/pages/feedItem/FeedItemPage.jsx
> +    dispatch(wsConnectedStart());
🔴 **Нужно исправить:**

Следует закрывать сокеты при уходе с соответствующих экранов, чтобы они не оставались на фоне.  Используйте для этого подходящий экшен и возвращаемую из `useEffect` функцию (https://disk.yandex.ru/i/odLVdl878JGqcA);

2023-02-07 14:09 UTC, randomroot commented on src/index.jsx
> +  applyMiddleware(socketMiddleware(wsUrlUser, wsUserActions, true))
🟢 **Отлично:**

Хорошо, что применили отдельные мидлвари под каждый из сокетов

2023-02-07 14:09 UTC, randomroot commented on src/components/ProtectedRoute/ProtectedRoute.jsx
> +    dispatch(wsUserConnectedStart());
🔴 **Нужно исправить:**

Не следует открывать сокет в момент попадания на защищенную страницу, он относится только к истории заказов, другие экраны его не используют

2023-02-07 14:09 UTC, randomroot commented on src/components/ProfileOrders/ProfileOrders.jsx
> +        <li key={index}>
🟡 **Можно улучшить:**

В качестве индекса лучше использовать идентификатор заказа, как более уникальный элемент, вместо индекса, чтобы было меньше ререндера

2023-02-07 14:09 UTC, randomroot commented on src/components/ProfileOrderModal/ProfileOrderModal.jsx
> +    <Modal isOpen close={back}>
🟡 **Можно улучшить:**

Немного нарушено форматирование кода в плане отступов

2023-02-07 14:09 UTC, randomroot commented on src/components/ProfileOrderItem/ProfileOrderItem.jsx
> +  resArr.map((el) => {
🟡 **Можно улучшить:**

Использования функции `map` в данном случае излишне, т.к. он генерирует на выходе массив, в данном случае целесообразно заменить её на `forEach` или `reduce` (см. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce)

2023-02-14 10:03 UTC, Maichonok commented
Приветствую, Михаил
Согласно: Проект не запускается по причине отличия регистра имени в import и в названии директории компонента IngredientsModal (см. https://disk.yandex.ru/i/iigns_2rKvqQ0Q). Обратите внимание, что этот момент важен на регистрозависимых системах, таких как Windows и может упускаться из виду на UNIX-подобных, в частности на MacOS или любой версии Linux;
===
В VSCode у меня корректно отображается, прилагаю скрин https://disk.yandex.ru/i/TPQ2s6XEJglYVA
и в самом файле репо https://disk.yandex.ru/i/Cjg3HWRhJBG8gw

2023-02-14 10:10 UTC, randomroot commented
@Maichonok, добрый день!

VS Code (https://disk.yandex.ru/i/B_DuooxaFo9l2A), Github (https://disk.yandex.ru/i/q1SUroWUBnBE-A).

Возможно, вы меняли название папки на правильное, однако Git не подцепил это изменение. Чтобы решить эту проблему воспользуйтесь этим способом: https://noteskeeper.ru/heritage/672/

2023-02-14 12:31 UTC, Maichonok commented
@randomroot спасибо, приняла к сведению.

2023-02-14 12:54 UTC, Maichonok commented on src/components/ProfileOrderModal/ProfileOrderModal.jsx
> +    <Modal isOpen close={back}>
have done

2023-02-14 12:55 UTC, Maichonok commented on src/components/Board/OrdersBoard.jsx
> +    <>
have done

2023-02-19 11:05 UTC, randomroot requested changes
**Здравствуйте!**

Вы успешно внесли множество изменений и улучшений в ваш проект, так держать, однако остались несколько моментов, которые следует также исправить для сдачи проекта в данном спринте:


- Не следует скрывать поле изменения пароля на экране "Профиль" по-умолчанию, у пользователя должна быть возможность изменить только пароль, не изменяя почту и/или имя;
- В истории заказов следует обеспечить скролл списка в рамках компонента, вместо скролла всей страницы сразу;
- Следует обеспечить подсветку активной иконки меню хедера, кроме подсветки текста (см. https://disk.yandex.ru/i/9RMQv0NMOY7JVQ);

Также, хотел бы уточнить свой комментарий по поводу `FormattedDate` - это компонент, который можно взять из библиотеки компонентов Яндекса: `import { FormattedDate
} from '@ya.praktikum/react-developer-burger-ui-components';`. Вариант с `Intl` тоже получился замечательно 👍 

**Хорошего вам дня и настроения!** 🐈

2023-02-19 11:05 UTC, randomroot commented on src/components/OrderItems/OrderItems.jsx
> +            {maxLength <= 5 &&
🟡 **Можно улучшить:**

JSX элементы рекомендуется оборачивать в круглые скобки в рамках таких выражений, чтобы избегать возможных проблем с автоформатированием кода (см. https://medium.com/as-a-coder/why-you-should-wrap-your-jsx-with-parentheses-d7670293e45)

2023-02-19 19:53 UTC, Maichonok commented
Доброго времени суток, Михаил, да, я сначала нашла информацию: https://yandex-practicum.github.io/react-developer-burger-ui-components/docs/formatted-date#properties, но решила поковыряться самостоятельно, зато теперь знаю, как это работает :) и подключается отдельно, спасибо, что отметили, мне приятно.

2023-02-19 19:55 UTC, Maichonok commented on src/components/OrderItems/OrderItems.jsx
> +            {maxLength <= 5 &&
здесь, к сожалению не поняла:  где улучшить? Ведь в этом файле у меня и так return (<div> ... </div>)

2023-02-19 20:22 UTC, randomroot commented on src/components/OrderItems/OrderItems.jsx
> +            {maxLength <= 5 &&
Добрый вечер, здесь подразумевалось, что в целом выражения, в который присутствует JSX лучше оборачивать скобки, т.е. например:

```jsx
{ maxLength <= 5 && (
       <Component />
   )}
```

2023-02-19 20:30 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**.

Вы молодец, что так внимательно изучили вопрос с отображением дат, любознательность - это очень важная и полезная черта для студента! 👍 

В качестве небольшого **улучшения** обратите внимание, что при переходе на экран "История заказов" гаснет подсветка у кнопки меню в хедере, целесообразно учитывать также и внутренние пути: т.е. для кнопки личный кабинет активное состояние лучше активировать на обоих путях `/profile` и `/profile/orders`.

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2023-02-20 10:37 UTC, Maichonok commented on src/components/OrderItems/OrderItems.jsx
> +            {maxLength <= 5 &&
> Добрый вечер, здесь подразумевалось, что в целом выражения, в который присутствует JSX лучше оборачивать скобки, т.е. например:
> 
> ```js
> { maxLength <= 5 && (
>        <Component />
>    )}
> ```
===
Prettier убирает эти оборачивающие скобки

2023-02-20 10:48 UTC, Maichonok commented
> 🟢 **Работа принята:**
> 
> Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**.
> 
> Вы молодец, что так внимательно изучили вопрос с отображением дат, любознательность - это очень важная и полезная черта для студента! 👍
> 
> В качестве небольшого **улучшения** обратите внимание, что при переходе на экран "История заказов" гаснет подсветка у кнопки меню в хедере, целесообразно учитывать также и внутренние пути: т.е. для кнопки личный кабинет активное состояние лучше активировать на обоих путях `/profile` и `/profile/orders`.
> 
> Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

===
спасибо за обратную связь. Всего хорошего!

2023-03-19 17:12 UTC, merged